# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YandexTestTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YandexTestTask
    pod 'SwiftFormat/CLI'
    pod 'SwiftLint'
    pod 'R.swift'
    pod 'Cartography', '~> 3.0'
    pod 'EasyStash'
    pod 'AMScrollingNavbar', :inhibit_warnings => true
    pod 'Charts'
    pod 'MaterialComponents/ActivityIndicator', :inhibit_warnings => true

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = "NO"
    end
end

end
