# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YandexTestTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YandexTestTask
    pod 'SwiftFormat/CLI'
    pod 'SwiftLint'
    pod 'R.swift'
    pod 'Cartography', '~> 3.0'
    pod 'EasyStash'
    pod 'AMScrollingNavbar'

end
